version: '3'

services:
  url2pdf:
    container_name: url2pdf
    build: .
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks: 
      - url2pdf

networks: 
  url2pdf:
    driver: bridge