apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
  creationTimestamp: "2020-03-18T13:39:53Z"
  generation: 32
  labels:
    app: url2pdf
  name: url2pdf
  namespace: default
  resourceVersion: "599199"
  selfLink: /apis/apps/v1/namespaces/default/deployments/url2pdf
  uid: f2ea5734-691d-11ea-be47-42010ab20fdc
spec:
  minReadySeconds: 3
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: url2pdf
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: url2pdf
    spec:
      containers:
      - env:
        - name: EMAIL_ADDRESS
          valueFrom:
            secretKeyRef:
              key: EMAIL_ADDRESS
              name: email.address
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: EMAIL_PASSWORD
              name: email.password
        image: gcr.io/url2pdf/url2pdf:v5
        imagePullPolicy: IfNotPresent
        name: url2pdf-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-20T10:06:51Z"
    lastUpdateTime: "2020-03-20T10:06:51Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-03-18T13:39:53Z"
    lastUpdateTime: "2020-03-20T10:52:38Z"
    message: ReplicaSet "url2pdf-5b75857747" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 32
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
