version: 2.0
jobs:
  build:
    docker:
      - image: node:10.15.0-slim
    working_directory: /usr/src/app
    steps:
      - checkout
      - run: 
          name: Run build
          command: yarn build

  deploy:
    machine: true
    working_directory: /usr/src/app
    steps:
      - checkout
      - run:
          name: Deploy GCP docker container
          command: |
            ???

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master